# number of boids
n_boids: 2

# behavior weights
w_a: 0.3
w_c: 0.3
w_s: 0.4

# neighborhood params
local_r: 0.5
local_theta: 180.0

# obstacle params
obs_r:  1.5 # for both see-to-avoid and pot field
step_angle : 0.174533 #10 in radian 
max_steering_angle : 6.28 #10 in radian