# number of boids
n_boids: 10

# behavior weights
w_a: &w_a 0.4 # Reusable anchor**
w_c: &w_c 0.7
w_s: &w_s 0.6
w_arrival: &w_arrival 0.1
w_steer_to_avoid: &w_steer_to_avoid 0.85

# neighborhood params
local_r: 1.9
local_theta: 360.0

# Desired goal
goal_x: 3 # 0
goal_y: 3 # 3.7
goal_radius: 0.5
goal_tolerance: 0.02
inter_goal_dist: 0.3 # Ratio of distance between two goals

# Set multiple goals as a list of [x, y, radius, tolerance]
goal_list: 
  - [3.0, 2.0, 5.0, 0.03]
  - [3.0, 2.0, 5.0, 0.03]

# Kinematic params
max_speed: 3.3
max_acc: 2.2

# Number of leader
n_leaders: 4 # Should not be greater than 7
leader_method: 0 # 0: Closest to goal, 1: ConvexHull
leader_type: 0 # 0: Dynamic, 1: Fixed

# Prioritized Acceleration
use_prioritized_acc: True
priority_list: 
  - '_arrival': *w_arrival
  # - '_steer_to_avoid': *w_steer_to_avoid
  # - '_potential_field': *w_steer_to_avoid
  - '_separation': *w_s
  - '_alignment': *w_a
  - '_cohesion': *w_c

# obstacle params
obs_r:  0.8 # for both see-to-avoid and pot field
step_angle : 0.174533 # 51 # 0.174533 #10 in radian 
max_steering_angle : 6.28 #10 in radian

# Arrival-specific params
hard_arrival: True # For hard arrival, the boid will ignore all other behaviors and only focus on arrival.