# number of boids
n_boids: 10

# behavior weights
w_a: 0.3
w_c: 0.3
w_s: 0.4

# neighborhood params
local_r: 0.5
local_theta: 180.0
#steer_to_avoid

step_angle : 0.174533 #10 in radian 
max_steering_angle : 1.0472 #10 in radian 

